version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    image: kultmet/foodgram_frontend
    # build: foodgram_frontend
    restart: always
    volumes:
      - ../frontend/:/app/result_build/

  web:
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    image: kultmet/foodgram_backend
    # build: foodgram_backend
    restart: always
    volumes:
      - static_value:/app/static/django/
      - media_value:/app/media/django/
      - orders_value:/app/orders/
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/django/
      - media_value:/var/html/media/django/
    depends_on:
      - web

volumes:
  static_value:
  media_value:

