# Generated by Django 3.2.16 on 2023-01-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIngredientWithUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(max_length=30, verbose_name='Еденици измерения')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='base_ingredient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='cuisine.baseingredientwithunits'),
            preserve_default=False,
        ),
    ]
