# Generated by Django 3.2.16 on 2023-02-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coockung_time',
            new_name='cooking_time',
        ),
    ]
