# Generated by Django 3.2.16 on 2023-02-16 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseingredientwithunits',
            options={'ordering': ['name'], 'verbose_name': 'Базовый ингредиент', 'verbose_name_plural': 'Базовые ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 16, 11, 2, 24, 685957, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
