# Generated by Django 3.2.16 on 2023-01-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_auto_20230120_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseingredientwithunits',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
