# Generated by Django 3.2.16 on 2023-02-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseingredientwithunits',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
