# Generated by Django 3.2.16 on 2023-02-18 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_auto_20230216_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-recipe__pub_date'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ['base_ingredient'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-recipe__pub_date'], 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'ordering': ['-recipe__pub_date'], 'verbose_name_plural': 'Связующая таблици для тегов'},
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1, 'Как ты можеш добавить игнредиент колличеством меньше 1?'), django.core.validators.MaxValueValidator(20000, 'Ты предлагаешь готовить для ВиллаРриба и ВиллаБаджо сразу?')], verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Ты хочешь чтоб это готовили? Добавь время приготовления!'), django.core.validators.MaxValueValidator(10080, 'Ты предлагаешь готовить сюрстремминг? Ограничение - 10080.')], verbose_name='Время приготовления'),
        ),
    ]
