# Generated by Django 3.2.16 on 2023-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_rename_coockung_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name_plural': 'Связующая таблици для тегов'},
        ),
        migrations.AddConstraint(
            model_name='tagrecipe',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='unique_tag_for_recipe'),
        ),
    ]
