# Generated by Django 3.2.16 on 2023-01-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseingredientwithunits',
            options={'verbose_name': 'Базовый ингредиент', 'verbose_name_plural': 'Базовые ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
