# Generated by Django 3.2.16 on 2023-02-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_alter_baseingredientwithunits_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseingredientwithunits',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
