# Generated by Django 3.2.16 on 2023-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_alter_baseingredientwithunits_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default=1, max_length=20, verbose_name='Еденици измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseingredientwithunits',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название ингредиента'),
        ),
    ]
