name: Django CI/CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Test with flake8
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub Backend
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Chack out the repo
      uses: actions/checkout@v2
    - name: Set up Docker Buidx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./backend/
        file: ./backend/Dockerfile
        push: true
        tags: kultmet/foodgram_backend:latest
    - name: Push to Docker Hub Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend/
        file: ./frontend/Dockerfile
        push: true
        tags: kultmet/foodgram_frontend:latest
  